### PR TITLE
fix: reduce API load on some page and add progress spinner

### PR DESCRIPTION
**Pull request by taro04**
@YasunoriMATSUOKA 
Please review.

To do : 
- Reduce Rest API access load by stopping continuous Rest API access on timer.
        -->  delete timer Observable
- To prohibit the user from sending transactions, display the loading is during data acquisition.
        -->  add progress spiner in html

### CODE REVIEW

**Comment by YasunoriMATSUOKA** [comment]
Memo: This PR is related to https://github.com/UnUniFi/utils/issues/238

**Review by YasunoriMATSUOKA — CHANGES_REQUESTED** [review]
@taro04 
I think you can add validation for following view component ts files easily.
How do you think about it?

- [ ] create
  - [ ] collateralDenom
  - [ ] principalDenom
- [ ] deposit
  - [ ] collateralDenom
- [ ] withdraw
  - [ ] collateralDenom
- [ ] issue
  - [ ] principalDenom
- [ ] clear
  - [ ] repaymentDenom

example ... In onSubmit method

```
    if (!collateralDenom) {
      this.snackBar.open(
        `Invalid Collateral. \n You need to wait until the correct collateral information is loaded. \n Please try again.`,
        'Close',
      );
      return;
    }
    if (!principalDenom) {
      this.snackBar.open(
        `Invalid Principal. \n You need to wait until the correct principal information is loaded. \n Please try again.`,
        'Close',
      );
      return;
    }
```

And, It would be helpful if you could unify the principal and repayment as they seemed to be mixed up. I noticed that the airdrop task description explains things like do ~ in the Principal field, so I'm sorry, but it would be helpful if you could put repayment or payment back into principal once again.

**Comment by taro04** [comment]
@YasunoriMATSUOKA 
Please review ( I wonder, reviewer is correct. ) 

- add snackbar message on the point that returns error
- repayment -> principal
- add principal and collateral verification to the view component

**Review by YasunoriMATSUOKA — APPROVED** [review]
LGTM

**Pull request merged**
